/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace DynamicValidatorRegistry {
  export type ActionThresholdStruct = {
    id: BytesLike;
    actionType: BigNumberish;
    requiredSignatures: BigNumberish;
    setAt: BigNumberish;
    description: string;
    active: boolean;
  };

  export type ActionThresholdStructOutput = [
    id: string,
    actionType: bigint,
    requiredSignatures: bigint,
    setAt: bigint,
    description: string,
    active: boolean
  ] & {
    id: string;
    actionType: bigint;
    requiredSignatures: bigint;
    setAt: bigint;
    description: string;
    active: boolean;
  };

  export type ValidatorStruct = {
    id: BytesLike;
    wallet: AddressLike;
    name: string;
    role: string;
    status: BigNumberish;
    addedAt: BigNumberish;
    removedAt: BigNumberish;
  };

  export type ValidatorStructOutput = [
    id: string,
    wallet: string,
    name: string,
    role: string,
    status: bigint,
    addedAt: bigint,
    removedAt: bigint
  ] & {
    id: string;
    wallet: string;
    name: string;
    role: string;
    status: bigint;
    addedAt: bigint;
    removedAt: bigint;
  };

  export type ConfigurationSnapshotStruct = {
    timestamp: BigNumberish;
    validatorCount: BigNumberish;
    activeCount: BigNumberish;
    snapshotHash: BytesLike;
    version: BigNumberish;
  };

  export type ConfigurationSnapshotStructOutput = [
    timestamp: bigint,
    validatorCount: bigint,
    activeCount: bigint,
    snapshotHash: string,
    version: bigint
  ] & {
    timestamp: bigint;
    validatorCount: bigint;
    activeCount: bigint;
    snapshotHash: string;
    version: bigint;
  };
}

export interface DynamicValidatorRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "UPGRADE_INTERFACE_VERSION"
      | "acceptOwnership"
      | "actionThresholds"
      | "activeValidators"
      | "addValidator"
      | "configurationHistory"
      | "configurationVersion"
      | "getActionThreshold"
      | "getActiveValidatorCount"
      | "getActiveValidators"
      | "getAllValidators"
      | "getConfigurationHistory"
      | "getConfigurationSnapshot"
      | "getRequiredSignatures"
      | "getValidator"
      | "getValidatorByWallet"
      | "getValidatorCount"
      | "initialize"
      | "isActiveValidator"
      | "maxValidators"
      | "minValidators"
      | "owner"
      | "pendingOwner"
      | "proxiableUUID"
      | "removeValidator"
      | "renounceOwnership"
      | "setActionThreshold"
      | "setMaxValidators"
      | "setMinValidators"
      | "transferOwnership"
      | "updateValidatorStatus"
      | "upgradeToAndCall"
      | "validatorIds"
      | "validators"
      | "walletToValidatorId"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ConfigurationVersioned"
      | "Initialized"
      | "OwnershipTransferStarted"
      | "OwnershipTransferred"
      | "ThresholdUpdated"
      | "Upgraded"
      | "ValidatorAdded"
      | "ValidatorCountChanged"
      | "ValidatorRemoved"
      | "ValidatorStatusChanged"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "actionThresholds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "activeValidators",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addValidator",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "configurationHistory",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "configurationVersion",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getActionThreshold",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveValidatorCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveValidators",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllValidators",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getConfigurationHistory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getConfigurationSnapshot",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRequiredSignatures",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getValidator",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getValidatorByWallet",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getValidatorCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isActiveValidator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "maxValidators",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minValidators",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeValidator",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setActionThreshold",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxValidators",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinValidators",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateValidatorStatus",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "validatorIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "validators",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "walletToValidatorId",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "actionThresholds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activeValidators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addValidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "configurationHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "configurationVersion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActionThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveValidatorCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveValidators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllValidators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getConfigurationHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getConfigurationSnapshot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRequiredSignatures",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getValidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getValidatorByWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getValidatorCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isActiveValidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxValidators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minValidators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeValidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setActionThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxValidators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinValidators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateValidatorStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validatorIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "validators", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "walletToValidatorId",
    data: BytesLike
  ): Result;
}

export namespace ConfigurationVersionedEvent {
  export type InputTuple = [
    version: BigNumberish,
    timestamp: BigNumberish,
    snapshotHash: BytesLike
  ];
  export type OutputTuple = [
    version: bigint,
    timestamp: bigint,
    snapshotHash: string
  ];
  export interface OutputObject {
    version: bigint;
    timestamp: bigint;
    snapshotHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferStartedEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ThresholdUpdatedEvent {
  export type InputTuple = [
    actionType: BigNumberish,
    oldRequired: BigNumberish,
    newRequired: BigNumberish
  ];
  export type OutputTuple = [
    actionType: bigint,
    oldRequired: bigint,
    newRequired: bigint
  ];
  export interface OutputObject {
    actionType: bigint;
    oldRequired: bigint;
    newRequired: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidatorAddedEvent {
  export type InputTuple = [
    validatorId: BytesLike,
    wallet: AddressLike,
    name: string,
    role: string
  ];
  export type OutputTuple = [
    validatorId: string,
    wallet: string,
    name: string,
    role: string
  ];
  export interface OutputObject {
    validatorId: string;
    wallet: string;
    name: string;
    role: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidatorCountChangedEvent {
  export type InputTuple = [
    newCount: BigNumberish,
    maxValidators: BigNumberish
  ];
  export type OutputTuple = [newCount: bigint, maxValidators: bigint];
  export interface OutputObject {
    newCount: bigint;
    maxValidators: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidatorRemovedEvent {
  export type InputTuple = [validatorId: BytesLike, wallet: AddressLike];
  export type OutputTuple = [validatorId: string, wallet: string];
  export interface OutputObject {
    validatorId: string;
    wallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidatorStatusChangedEvent {
  export type InputTuple = [
    validatorId: BytesLike,
    oldStatus: BigNumberish,
    newStatus: BigNumberish
  ];
  export type OutputTuple = [
    validatorId: string,
    oldStatus: bigint,
    newStatus: bigint
  ];
  export interface OutputObject {
    validatorId: string;
    oldStatus: bigint;
    newStatus: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DynamicValidatorRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): DynamicValidatorRegistry;
  waitForDeployment(): Promise<this>;

  interface: DynamicValidatorRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  actionThresholds: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, string, boolean] & {
        id: string;
        actionType: bigint;
        requiredSignatures: bigint;
        setAt: bigint;
        description: string;
        active: boolean;
      }
    ],
    "view"
  >;

  activeValidators: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  addValidator: TypedContractMethod<
    [wallet: AddressLike, name: string, role: string],
    [string],
    "nonpayable"
  >;

  configurationHistory: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, string, bigint] & {
        timestamp: bigint;
        validatorCount: bigint;
        activeCount: bigint;
        snapshotHash: string;
        version: bigint;
      }
    ],
    "view"
  >;

  configurationVersion: TypedContractMethod<[], [bigint], "view">;

  getActionThreshold: TypedContractMethod<
    [actionType: BigNumberish],
    [DynamicValidatorRegistry.ActionThresholdStructOutput],
    "view"
  >;

  getActiveValidatorCount: TypedContractMethod<[], [bigint], "view">;

  getActiveValidators: TypedContractMethod<[], [string[]], "view">;

  getAllValidators: TypedContractMethod<
    [],
    [DynamicValidatorRegistry.ValidatorStructOutput[]],
    "view"
  >;

  getConfigurationHistory: TypedContractMethod<
    [],
    [DynamicValidatorRegistry.ConfigurationSnapshotStructOutput[]],
    "view"
  >;

  getConfigurationSnapshot: TypedContractMethod<
    [version: BigNumberish],
    [DynamicValidatorRegistry.ConfigurationSnapshotStructOutput],
    "view"
  >;

  getRequiredSignatures: TypedContractMethod<
    [actionType: BigNumberish],
    [bigint],
    "view"
  >;

  getValidator: TypedContractMethod<
    [validatorId: BytesLike],
    [DynamicValidatorRegistry.ValidatorStructOutput],
    "view"
  >;

  getValidatorByWallet: TypedContractMethod<
    [wallet: AddressLike],
    [DynamicValidatorRegistry.ValidatorStructOutput],
    "view"
  >;

  getValidatorCount: TypedContractMethod<[], [bigint], "view">;

  initialize: TypedContractMethod<[owner: AddressLike], [void], "nonpayable">;

  isActiveValidator: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  maxValidators: TypedContractMethod<[], [bigint], "view">;

  minValidators: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pendingOwner: TypedContractMethod<[], [string], "view">;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  removeValidator: TypedContractMethod<
    [validatorId: BytesLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setActionThreshold: TypedContractMethod<
    [
      actionType: BigNumberish,
      requiredSignatures: BigNumberish,
      description: string
    ],
    [void],
    "nonpayable"
  >;

  setMaxValidators: TypedContractMethod<
    [newMax: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMinValidators: TypedContractMethod<
    [newMin: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateValidatorStatus: TypedContractMethod<
    [validatorId: BytesLike, newStatus: BigNumberish],
    [void],
    "nonpayable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  validatorIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  validators: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, string, bigint, bigint, bigint] & {
        id: string;
        wallet: string;
        name: string;
        role: string;
        status: bigint;
        addedAt: bigint;
        removedAt: bigint;
      }
    ],
    "view"
  >;

  walletToValidatorId: TypedContractMethod<
    [arg0: AddressLike],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "actionThresholds"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, string, boolean] & {
        id: string;
        actionType: bigint;
        requiredSignatures: bigint;
        setAt: bigint;
        description: string;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "activeValidators"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "addValidator"
  ): TypedContractMethod<
    [wallet: AddressLike, name: string, role: string],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "configurationHistory"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, string, bigint] & {
        timestamp: bigint;
        validatorCount: bigint;
        activeCount: bigint;
        snapshotHash: string;
        version: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "configurationVersion"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getActionThreshold"
  ): TypedContractMethod<
    [actionType: BigNumberish],
    [DynamicValidatorRegistry.ActionThresholdStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getActiveValidatorCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getActiveValidators"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getAllValidators"
  ): TypedContractMethod<
    [],
    [DynamicValidatorRegistry.ValidatorStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getConfigurationHistory"
  ): TypedContractMethod<
    [],
    [DynamicValidatorRegistry.ConfigurationSnapshotStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getConfigurationSnapshot"
  ): TypedContractMethod<
    [version: BigNumberish],
    [DynamicValidatorRegistry.ConfigurationSnapshotStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRequiredSignatures"
  ): TypedContractMethod<[actionType: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getValidator"
  ): TypedContractMethod<
    [validatorId: BytesLike],
    [DynamicValidatorRegistry.ValidatorStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getValidatorByWallet"
  ): TypedContractMethod<
    [wallet: AddressLike],
    [DynamicValidatorRegistry.ValidatorStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getValidatorCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<[owner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isActiveValidator"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "maxValidators"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minValidators"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeValidator"
  ): TypedContractMethod<[validatorId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setActionThreshold"
  ): TypedContractMethod<
    [
      actionType: BigNumberish,
      requiredSignatures: BigNumberish,
      description: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMaxValidators"
  ): TypedContractMethod<[newMax: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMinValidators"
  ): TypedContractMethod<[newMin: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateValidatorStatus"
  ): TypedContractMethod<
    [validatorId: BytesLike, newStatus: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "validatorIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "validators"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, string, bigint, bigint, bigint] & {
        id: string;
        wallet: string;
        name: string;
        role: string;
        status: bigint;
        addedAt: bigint;
        removedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "walletToValidatorId"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;

  getEvent(
    key: "ConfigurationVersioned"
  ): TypedContractEvent<
    ConfigurationVersionedEvent.InputTuple,
    ConfigurationVersionedEvent.OutputTuple,
    ConfigurationVersionedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferStarted"
  ): TypedContractEvent<
    OwnershipTransferStartedEvent.InputTuple,
    OwnershipTransferStartedEvent.OutputTuple,
    OwnershipTransferStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ThresholdUpdated"
  ): TypedContractEvent<
    ThresholdUpdatedEvent.InputTuple,
    ThresholdUpdatedEvent.OutputTuple,
    ThresholdUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;
  getEvent(
    key: "ValidatorAdded"
  ): TypedContractEvent<
    ValidatorAddedEvent.InputTuple,
    ValidatorAddedEvent.OutputTuple,
    ValidatorAddedEvent.OutputObject
  >;
  getEvent(
    key: "ValidatorCountChanged"
  ): TypedContractEvent<
    ValidatorCountChangedEvent.InputTuple,
    ValidatorCountChangedEvent.OutputTuple,
    ValidatorCountChangedEvent.OutputObject
  >;
  getEvent(
    key: "ValidatorRemoved"
  ): TypedContractEvent<
    ValidatorRemovedEvent.InputTuple,
    ValidatorRemovedEvent.OutputTuple,
    ValidatorRemovedEvent.OutputObject
  >;
  getEvent(
    key: "ValidatorStatusChanged"
  ): TypedContractEvent<
    ValidatorStatusChangedEvent.InputTuple,
    ValidatorStatusChangedEvent.OutputTuple,
    ValidatorStatusChangedEvent.OutputObject
  >;

  filters: {
    "ConfigurationVersioned(uint256,uint256,bytes32)": TypedContractEvent<
      ConfigurationVersionedEvent.InputTuple,
      ConfigurationVersionedEvent.OutputTuple,
      ConfigurationVersionedEvent.OutputObject
    >;
    ConfigurationVersioned: TypedContractEvent<
      ConfigurationVersionedEvent.InputTuple,
      ConfigurationVersionedEvent.OutputTuple,
      ConfigurationVersionedEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "OwnershipTransferStarted(address,address)": TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;
    OwnershipTransferStarted: TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ThresholdUpdated(uint8,uint8,uint8)": TypedContractEvent<
      ThresholdUpdatedEvent.InputTuple,
      ThresholdUpdatedEvent.OutputTuple,
      ThresholdUpdatedEvent.OutputObject
    >;
    ThresholdUpdated: TypedContractEvent<
      ThresholdUpdatedEvent.InputTuple,
      ThresholdUpdatedEvent.OutputTuple,
      ThresholdUpdatedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;

    "ValidatorAdded(bytes32,address,string,string)": TypedContractEvent<
      ValidatorAddedEvent.InputTuple,
      ValidatorAddedEvent.OutputTuple,
      ValidatorAddedEvent.OutputObject
    >;
    ValidatorAdded: TypedContractEvent<
      ValidatorAddedEvent.InputTuple,
      ValidatorAddedEvent.OutputTuple,
      ValidatorAddedEvent.OutputObject
    >;

    "ValidatorCountChanged(uint256,uint256)": TypedContractEvent<
      ValidatorCountChangedEvent.InputTuple,
      ValidatorCountChangedEvent.OutputTuple,
      ValidatorCountChangedEvent.OutputObject
    >;
    ValidatorCountChanged: TypedContractEvent<
      ValidatorCountChangedEvent.InputTuple,
      ValidatorCountChangedEvent.OutputTuple,
      ValidatorCountChangedEvent.OutputObject
    >;

    "ValidatorRemoved(bytes32,address)": TypedContractEvent<
      ValidatorRemovedEvent.InputTuple,
      ValidatorRemovedEvent.OutputTuple,
      ValidatorRemovedEvent.OutputObject
    >;
    ValidatorRemoved: TypedContractEvent<
      ValidatorRemovedEvent.InputTuple,
      ValidatorRemovedEvent.OutputTuple,
      ValidatorRemovedEvent.OutputObject
    >;

    "ValidatorStatusChanged(bytes32,uint8,uint8)": TypedContractEvent<
      ValidatorStatusChangedEvent.InputTuple,
      ValidatorStatusChangedEvent.OutputTuple,
      ValidatorStatusChangedEvent.OutputObject
    >;
    ValidatorStatusChanged: TypedContractEvent<
      ValidatorStatusChangedEvent.InputTuple,
      ValidatorStatusChangedEvent.OutputTuple,
      ValidatorStatusChangedEvent.OutputObject
    >;
  };
}
