/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace Checkpoints {
  export type Checkpoint208Struct = {
    _key: BigNumberish;
    _value: BigNumberish;
  };

  export type Checkpoint208StructOutput = [_key: bigint, _value: bigint] & {
    _key: bigint;
    _value: bigint;
  };
}

export declare namespace GovernanceTokenV2 {
  export type BlacklistRequestStruct = {
    account: AddressLike;
    reason: string;
    requestedAt: BigNumberish;
    executed: boolean;
    governanceProposalId: BytesLike;
  };

  export type BlacklistRequestStructOutput = [
    account: string,
    reason: string,
    requestedAt: bigint,
    executed: boolean,
    governanceProposalId: string
  ] & {
    account: string;
    reason: string;
    requestedAt: bigint;
    executed: boolean;
    governanceProposalId: string;
  };

  export type MintRequestStruct = {
    recipient: AddressLike;
    amount: BigNumberish;
    reason: string;
    requestedAt: BigNumberish;
    executed: boolean;
    governanceProposalId: BytesLike;
  };

  export type MintRequestStructOutput = [
    recipient: string,
    amount: bigint,
    reason: string,
    requestedAt: bigint,
    executed: boolean,
    governanceProposalId: string
  ] & {
    recipient: string;
    amount: bigint;
    reason: string;
    requestedAt: bigint;
    executed: boolean;
    governanceProposalId: string;
  };
}

export interface GovernanceTokenV2Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "CLOCK_MODE"
      | "DOMAIN_SEPARATOR"
      | "MAX_SUPPLY"
      | "UPGRADE_INTERFACE_VERSION"
      | "acceptOwnership"
      | "allowance"
      | "approve"
      | "balanceOf"
      | "blacklist"
      | "blacklistRequestIds"
      | "blacklistRequests"
      | "blacklistTimestamp"
      | "burn"
      | "burnFrom"
      | "cancelMintRequest"
      | "checkpoints"
      | "clock"
      | "decimals"
      | "delegate"
      | "delegateBySig"
      | "delegates"
      | "eip712Domain"
      | "executeBlacklist"
      | "executeMint"
      | "getBlacklistRequest"
      | "getBlacklistRequestIds"
      | "getBlacklistTimestamp"
      | "getBlacklistedAddresses"
      | "getMintRequest"
      | "getMintRequestIds"
      | "getPastTotalSupply"
      | "getPastVotes"
      | "getPendingBlacklistRequests"
      | "getPendingMintRequests"
      | "getRemainingMintCapacity"
      | "getTotalMinted"
      | "getVotes"
      | "initialize"
      | "isBlacklisted"
      | "mintRequestIds"
      | "mintRequests"
      | "name"
      | "nonces"
      | "numCheckpoints"
      | "owner"
      | "pendingOwner"
      | "permit"
      | "proxiableUUID"
      | "removeFromBlacklist"
      | "renounceOwnership"
      | "requestBlacklist"
      | "requestBlacklistRemoval"
      | "requestMint"
      | "symbol"
      | "totalBlacklistRequests"
      | "totalMintRequested"
      | "totalSupply"
      | "transfer"
      | "transferFrom"
      | "transferOwnership"
      | "upgradeToAndCall"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AddressBlacklisted"
      | "AddressUnblacklisted"
      | "Approval"
      | "BlacklistExecuted"
      | "BlacklistRemovalProposed"
      | "BlacklistRequested"
      | "DelegateChanged"
      | "DelegateVotesChanged"
      | "EIP712DomainChanged"
      | "Initialized"
      | "MintCancelled"
      | "MintExecuted"
      | "MintRequested"
      | "OwnershipTransferStarted"
      | "OwnershipTransferred"
      | "Transfer"
      | "Upgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "CLOCK_MODE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DOMAIN_SEPARATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_SUPPLY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allowance",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "blacklist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "blacklistRequestIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "blacklistRequests",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "blacklistTimestamp",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "burn", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "burnFrom",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelMintRequest",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "checkpoints",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "clock", values?: undefined): string;
  encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "delegate",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "delegateBySig",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "delegates",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "eip712Domain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeBlacklist",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeMint",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBlacklistRequest",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBlacklistRequestIds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBlacklistTimestamp",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBlacklistedAddresses",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMintRequest",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMintRequestIds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPastTotalSupply",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPastVotes",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingBlacklistRequests",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingMintRequests",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRemainingMintCapacity",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalMinted",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getVotes",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isBlacklisted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mintRequestIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mintRequests",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "nonces", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "numCheckpoints",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "permit",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeFromBlacklist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestBlacklist",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "requestBlacklistRemoval",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "requestMint",
    values: [AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalBlacklistRequests",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalMintRequested",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "CLOCK_MODE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DOMAIN_SEPARATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MAX_SUPPLY", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allowance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "blacklist", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "blacklistRequestIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "blacklistRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "blacklistTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "burn", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "burnFrom", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelMintRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkpoints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "clock", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "delegate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "delegateBySig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "delegates", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "eip712Domain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeBlacklist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeMint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBlacklistRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBlacklistRequestIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBlacklistTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBlacklistedAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMintRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMintRequestIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPastTotalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPastVotes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingBlacklistRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingMintRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRemainingMintCapacity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalMinted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getVotes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isBlacklisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintRequestIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nonces", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "numCheckpoints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "permit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeFromBlacklist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestBlacklist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestBlacklistRemoval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestMint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalBlacklistRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalMintRequested",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
}

export namespace AddressBlacklistedEvent {
  export type InputTuple = [
    account: AddressLike,
    reason: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    account: string,
    reason: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    account: string;
    reason: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AddressUnblacklistedEvent {
  export type InputTuple = [account: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [account: string, timestamp: bigint];
  export interface OutputObject {
    account: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    spender: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [owner: string, spender: string, value: bigint];
  export interface OutputObject {
    owner: string;
    spender: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BlacklistExecutedEvent {
  export type InputTuple = [
    requestId: BytesLike,
    account: AddressLike,
    governanceProposalId: BytesLike,
    burntAmount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    requestId: string,
    account: string,
    governanceProposalId: string,
    burntAmount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    requestId: string;
    account: string;
    governanceProposalId: string;
    burntAmount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BlacklistRemovalProposedEvent {
  export type InputTuple = [
    requestId: BytesLike,
    account: AddressLike,
    reason: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    requestId: string,
    account: string,
    reason: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    requestId: string;
    account: string;
    reason: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BlacklistRequestedEvent {
  export type InputTuple = [
    requestId: BytesLike,
    account: AddressLike,
    reason: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    requestId: string,
    account: string,
    reason: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    requestId: string;
    account: string;
    reason: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DelegateChangedEvent {
  export type InputTuple = [
    delegator: AddressLike,
    fromDelegate: AddressLike,
    toDelegate: AddressLike
  ];
  export type OutputTuple = [
    delegator: string,
    fromDelegate: string,
    toDelegate: string
  ];
  export interface OutputObject {
    delegator: string;
    fromDelegate: string;
    toDelegate: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DelegateVotesChangedEvent {
  export type InputTuple = [
    delegate: AddressLike,
    previousVotes: BigNumberish,
    newVotes: BigNumberish
  ];
  export type OutputTuple = [
    delegate: string,
    previousVotes: bigint,
    newVotes: bigint
  ];
  export interface OutputObject {
    delegate: string;
    previousVotes: bigint;
    newVotes: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EIP712DomainChangedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MintCancelledEvent {
  export type InputTuple = [
    requestId: BytesLike,
    recipient: AddressLike,
    amount: BigNumberish,
    reason: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    requestId: string,
    recipient: string,
    amount: bigint,
    reason: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    requestId: string;
    recipient: string;
    amount: bigint;
    reason: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MintExecutedEvent {
  export type InputTuple = [
    requestId: BytesLike,
    recipient: AddressLike,
    amount: BigNumberish,
    governanceProposalId: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    requestId: string,
    recipient: string,
    amount: bigint,
    governanceProposalId: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    requestId: string;
    recipient: string;
    amount: bigint;
    governanceProposalId: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MintRequestedEvent {
  export type InputTuple = [
    requestId: BytesLike,
    recipient: AddressLike,
    amount: BigNumberish,
    reason: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    requestId: string,
    recipient: string,
    amount: bigint,
    reason: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    requestId: string;
    recipient: string;
    amount: bigint;
    reason: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferStartedEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, value: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GovernanceTokenV2 extends BaseContract {
  connect(runner?: ContractRunner | null): GovernanceTokenV2;
  waitForDeployment(): Promise<this>;

  interface: GovernanceTokenV2Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CLOCK_MODE: TypedContractMethod<[], [string], "view">;

  DOMAIN_SEPARATOR: TypedContractMethod<[], [string], "view">;

  MAX_SUPPLY: TypedContractMethod<[], [bigint], "view">;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  allowance: TypedContractMethod<
    [owner: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;

  approve: TypedContractMethod<
    [spender: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  balanceOf: TypedContractMethod<[account: AddressLike], [bigint], "view">;

  blacklist: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  blacklistRequestIds: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  blacklistRequests: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, boolean, string] & {
        account: string;
        reason: string;
        requestedAt: bigint;
        executed: boolean;
        governanceProposalId: string;
      }
    ],
    "view"
  >;

  blacklistTimestamp: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  burn: TypedContractMethod<[value: BigNumberish], [void], "nonpayable">;

  burnFrom: TypedContractMethod<
    [account: AddressLike, value: BigNumberish],
    [void],
    "nonpayable"
  >;

  cancelMintRequest: TypedContractMethod<
    [requestId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;

  checkpoints: TypedContractMethod<
    [account: AddressLike, pos: BigNumberish],
    [Checkpoints.Checkpoint208StructOutput],
    "view"
  >;

  clock: TypedContractMethod<[], [bigint], "view">;

  decimals: TypedContractMethod<[], [bigint], "view">;

  delegate: TypedContractMethod<[delegatee: AddressLike], [void], "nonpayable">;

  delegateBySig: TypedContractMethod<
    [
      delegatee: AddressLike,
      nonce: BigNumberish,
      expiry: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  delegates: TypedContractMethod<[account: AddressLike], [string], "view">;

  eip712Domain: TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;

  executeBlacklist: TypedContractMethod<
    [requestId: BytesLike, proposalId: BytesLike],
    [void],
    "nonpayable"
  >;

  executeMint: TypedContractMethod<
    [requestId: BytesLike, proposalId: BytesLike],
    [void],
    "nonpayable"
  >;

  getBlacklistRequest: TypedContractMethod<
    [requestId: BytesLike],
    [GovernanceTokenV2.BlacklistRequestStructOutput],
    "view"
  >;

  getBlacklistRequestIds: TypedContractMethod<[], [string[]], "view">;

  getBlacklistTimestamp: TypedContractMethod<
    [account: AddressLike],
    [bigint],
    "view"
  >;

  getBlacklistedAddresses: TypedContractMethod<[], [string[]], "view">;

  getMintRequest: TypedContractMethod<
    [requestId: BytesLike],
    [GovernanceTokenV2.MintRequestStructOutput],
    "view"
  >;

  getMintRequestIds: TypedContractMethod<[], [string[]], "view">;

  getPastTotalSupply: TypedContractMethod<
    [timepoint: BigNumberish],
    [bigint],
    "view"
  >;

  getPastVotes: TypedContractMethod<
    [account: AddressLike, timepoint: BigNumberish],
    [bigint],
    "view"
  >;

  getPendingBlacklistRequests: TypedContractMethod<
    [],
    [GovernanceTokenV2.BlacklistRequestStructOutput[]],
    "view"
  >;

  getPendingMintRequests: TypedContractMethod<
    [],
    [GovernanceTokenV2.MintRequestStructOutput[]],
    "view"
  >;

  getRemainingMintCapacity: TypedContractMethod<[], [bigint], "view">;

  getTotalMinted: TypedContractMethod<[], [bigint], "view">;

  getVotes: TypedContractMethod<[account: AddressLike], [bigint], "view">;

  initialize: TypedContractMethod<[owner: AddressLike], [void], "nonpayable">;

  isBlacklisted: TypedContractMethod<[account: AddressLike], [boolean], "view">;

  mintRequestIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  mintRequests: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, string, bigint, boolean, string] & {
        recipient: string;
        amount: bigint;
        reason: string;
        requestedAt: bigint;
        executed: boolean;
        governanceProposalId: string;
      }
    ],
    "view"
  >;

  name: TypedContractMethod<[], [string], "view">;

  nonces: TypedContractMethod<[owner: AddressLike], [bigint], "view">;

  numCheckpoints: TypedContractMethod<[account: AddressLike], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pendingOwner: TypedContractMethod<[], [string], "view">;

  permit: TypedContractMethod<
    [
      owner: AddressLike,
      spender: AddressLike,
      value: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  removeFromBlacklist: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  requestBlacklist: TypedContractMethod<
    [account: AddressLike, reason: string],
    [string],
    "nonpayable"
  >;

  requestBlacklistRemoval: TypedContractMethod<
    [account: AddressLike, reason: string],
    [string],
    "nonpayable"
  >;

  requestMint: TypedContractMethod<
    [recipient: AddressLike, amount: BigNumberish, reason: string],
    [string],
    "nonpayable"
  >;

  symbol: TypedContractMethod<[], [string], "view">;

  totalBlacklistRequests: TypedContractMethod<[], [bigint], "view">;

  totalMintRequested: TypedContractMethod<[], [bigint], "view">;

  totalSupply: TypedContractMethod<[], [bigint], "view">;

  transfer: TypedContractMethod<
    [to: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  transferFrom: TypedContractMethod<
    [from: AddressLike, to: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CLOCK_MODE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DOMAIN_SEPARATOR"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MAX_SUPPLY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "allowance"
  ): TypedContractMethod<
    [owner: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [spender: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "blacklist"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "blacklistRequestIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "blacklistRequests"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, boolean, string] & {
        account: string;
        reason: string;
        requestedAt: bigint;
        executed: boolean;
        governanceProposalId: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "blacklistTimestamp"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "burn"
  ): TypedContractMethod<[value: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "burnFrom"
  ): TypedContractMethod<
    [account: AddressLike, value: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cancelMintRequest"
  ): TypedContractMethod<
    [requestId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "checkpoints"
  ): TypedContractMethod<
    [account: AddressLike, pos: BigNumberish],
    [Checkpoints.Checkpoint208StructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "clock"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "decimals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "delegate"
  ): TypedContractMethod<[delegatee: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "delegateBySig"
  ): TypedContractMethod<
    [
      delegatee: AddressLike,
      nonce: BigNumberish,
      expiry: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "delegates"
  ): TypedContractMethod<[account: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "eip712Domain"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "executeBlacklist"
  ): TypedContractMethod<
    [requestId: BytesLike, proposalId: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeMint"
  ): TypedContractMethod<
    [requestId: BytesLike, proposalId: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getBlacklistRequest"
  ): TypedContractMethod<
    [requestId: BytesLike],
    [GovernanceTokenV2.BlacklistRequestStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBlacklistRequestIds"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getBlacklistTimestamp"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getBlacklistedAddresses"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getMintRequest"
  ): TypedContractMethod<
    [requestId: BytesLike],
    [GovernanceTokenV2.MintRequestStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMintRequestIds"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getPastTotalSupply"
  ): TypedContractMethod<[timepoint: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPastVotes"
  ): TypedContractMethod<
    [account: AddressLike, timepoint: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPendingBlacklistRequests"
  ): TypedContractMethod<
    [],
    [GovernanceTokenV2.BlacklistRequestStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPendingMintRequests"
  ): TypedContractMethod<
    [],
    [GovernanceTokenV2.MintRequestStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRemainingMintCapacity"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTotalMinted"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getVotes"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<[owner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isBlacklisted"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "mintRequestIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "mintRequests"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, string, bigint, boolean, string] & {
        recipient: string;
        amount: bigint;
        reason: string;
        requestedAt: bigint;
        executed: boolean;
        governanceProposalId: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "nonces"
  ): TypedContractMethod<[owner: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "numCheckpoints"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "permit"
  ): TypedContractMethod<
    [
      owner: AddressLike,
      spender: AddressLike,
      value: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeFromBlacklist"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestBlacklist"
  ): TypedContractMethod<
    [account: AddressLike, reason: string],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestBlacklistRemoval"
  ): TypedContractMethod<
    [account: AddressLike, reason: string],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestMint"
  ): TypedContractMethod<
    [recipient: AddressLike, amount: BigNumberish, reason: string],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalBlacklistRequests"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalMintRequested"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transfer"
  ): TypedContractMethod<
    [to: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getEvent(
    key: "AddressBlacklisted"
  ): TypedContractEvent<
    AddressBlacklistedEvent.InputTuple,
    AddressBlacklistedEvent.OutputTuple,
    AddressBlacklistedEvent.OutputObject
  >;
  getEvent(
    key: "AddressUnblacklisted"
  ): TypedContractEvent<
    AddressUnblacklistedEvent.InputTuple,
    AddressUnblacklistedEvent.OutputTuple,
    AddressUnblacklistedEvent.OutputObject
  >;
  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "BlacklistExecuted"
  ): TypedContractEvent<
    BlacklistExecutedEvent.InputTuple,
    BlacklistExecutedEvent.OutputTuple,
    BlacklistExecutedEvent.OutputObject
  >;
  getEvent(
    key: "BlacklistRemovalProposed"
  ): TypedContractEvent<
    BlacklistRemovalProposedEvent.InputTuple,
    BlacklistRemovalProposedEvent.OutputTuple,
    BlacklistRemovalProposedEvent.OutputObject
  >;
  getEvent(
    key: "BlacklistRequested"
  ): TypedContractEvent<
    BlacklistRequestedEvent.InputTuple,
    BlacklistRequestedEvent.OutputTuple,
    BlacklistRequestedEvent.OutputObject
  >;
  getEvent(
    key: "DelegateChanged"
  ): TypedContractEvent<
    DelegateChangedEvent.InputTuple,
    DelegateChangedEvent.OutputTuple,
    DelegateChangedEvent.OutputObject
  >;
  getEvent(
    key: "DelegateVotesChanged"
  ): TypedContractEvent<
    DelegateVotesChangedEvent.InputTuple,
    DelegateVotesChangedEvent.OutputTuple,
    DelegateVotesChangedEvent.OutputObject
  >;
  getEvent(
    key: "EIP712DomainChanged"
  ): TypedContractEvent<
    EIP712DomainChangedEvent.InputTuple,
    EIP712DomainChangedEvent.OutputTuple,
    EIP712DomainChangedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "MintCancelled"
  ): TypedContractEvent<
    MintCancelledEvent.InputTuple,
    MintCancelledEvent.OutputTuple,
    MintCancelledEvent.OutputObject
  >;
  getEvent(
    key: "MintExecuted"
  ): TypedContractEvent<
    MintExecutedEvent.InputTuple,
    MintExecutedEvent.OutputTuple,
    MintExecutedEvent.OutputObject
  >;
  getEvent(
    key: "MintRequested"
  ): TypedContractEvent<
    MintRequestedEvent.InputTuple,
    MintRequestedEvent.OutputTuple,
    MintRequestedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferStarted"
  ): TypedContractEvent<
    OwnershipTransferStartedEvent.InputTuple,
    OwnershipTransferStartedEvent.OutputTuple,
    OwnershipTransferStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "AddressBlacklisted(address,string,uint256)": TypedContractEvent<
      AddressBlacklistedEvent.InputTuple,
      AddressBlacklistedEvent.OutputTuple,
      AddressBlacklistedEvent.OutputObject
    >;
    AddressBlacklisted: TypedContractEvent<
      AddressBlacklistedEvent.InputTuple,
      AddressBlacklistedEvent.OutputTuple,
      AddressBlacklistedEvent.OutputObject
    >;

    "AddressUnblacklisted(address,uint256)": TypedContractEvent<
      AddressUnblacklistedEvent.InputTuple,
      AddressUnblacklistedEvent.OutputTuple,
      AddressUnblacklistedEvent.OutputObject
    >;
    AddressUnblacklisted: TypedContractEvent<
      AddressUnblacklistedEvent.InputTuple,
      AddressUnblacklistedEvent.OutputTuple,
      AddressUnblacklistedEvent.OutputObject
    >;

    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "BlacklistExecuted(bytes32,address,bytes32,uint256,uint256)": TypedContractEvent<
      BlacklistExecutedEvent.InputTuple,
      BlacklistExecutedEvent.OutputTuple,
      BlacklistExecutedEvent.OutputObject
    >;
    BlacklistExecuted: TypedContractEvent<
      BlacklistExecutedEvent.InputTuple,
      BlacklistExecutedEvent.OutputTuple,
      BlacklistExecutedEvent.OutputObject
    >;

    "BlacklistRemovalProposed(bytes32,address,string,uint256)": TypedContractEvent<
      BlacklistRemovalProposedEvent.InputTuple,
      BlacklistRemovalProposedEvent.OutputTuple,
      BlacklistRemovalProposedEvent.OutputObject
    >;
    BlacklistRemovalProposed: TypedContractEvent<
      BlacklistRemovalProposedEvent.InputTuple,
      BlacklistRemovalProposedEvent.OutputTuple,
      BlacklistRemovalProposedEvent.OutputObject
    >;

    "BlacklistRequested(bytes32,address,string,uint256)": TypedContractEvent<
      BlacklistRequestedEvent.InputTuple,
      BlacklistRequestedEvent.OutputTuple,
      BlacklistRequestedEvent.OutputObject
    >;
    BlacklistRequested: TypedContractEvent<
      BlacklistRequestedEvent.InputTuple,
      BlacklistRequestedEvent.OutputTuple,
      BlacklistRequestedEvent.OutputObject
    >;

    "DelegateChanged(address,address,address)": TypedContractEvent<
      DelegateChangedEvent.InputTuple,
      DelegateChangedEvent.OutputTuple,
      DelegateChangedEvent.OutputObject
    >;
    DelegateChanged: TypedContractEvent<
      DelegateChangedEvent.InputTuple,
      DelegateChangedEvent.OutputTuple,
      DelegateChangedEvent.OutputObject
    >;

    "DelegateVotesChanged(address,uint256,uint256)": TypedContractEvent<
      DelegateVotesChangedEvent.InputTuple,
      DelegateVotesChangedEvent.OutputTuple,
      DelegateVotesChangedEvent.OutputObject
    >;
    DelegateVotesChanged: TypedContractEvent<
      DelegateVotesChangedEvent.InputTuple,
      DelegateVotesChangedEvent.OutputTuple,
      DelegateVotesChangedEvent.OutputObject
    >;

    "EIP712DomainChanged()": TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;
    EIP712DomainChanged: TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "MintCancelled(bytes32,address,uint256,string,uint256)": TypedContractEvent<
      MintCancelledEvent.InputTuple,
      MintCancelledEvent.OutputTuple,
      MintCancelledEvent.OutputObject
    >;
    MintCancelled: TypedContractEvent<
      MintCancelledEvent.InputTuple,
      MintCancelledEvent.OutputTuple,
      MintCancelledEvent.OutputObject
    >;

    "MintExecuted(bytes32,address,uint256,bytes32,uint256)": TypedContractEvent<
      MintExecutedEvent.InputTuple,
      MintExecutedEvent.OutputTuple,
      MintExecutedEvent.OutputObject
    >;
    MintExecuted: TypedContractEvent<
      MintExecutedEvent.InputTuple,
      MintExecutedEvent.OutputTuple,
      MintExecutedEvent.OutputObject
    >;

    "MintRequested(bytes32,address,uint256,string,uint256)": TypedContractEvent<
      MintRequestedEvent.InputTuple,
      MintRequestedEvent.OutputTuple,
      MintRequestedEvent.OutputObject
    >;
    MintRequested: TypedContractEvent<
      MintRequestedEvent.InputTuple,
      MintRequestedEvent.OutputTuple,
      MintRequestedEvent.OutputObject
    >;

    "OwnershipTransferStarted(address,address)": TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;
    OwnershipTransferStarted: TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
