/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace PayoutExecutor {
  export type PayoutRequestStruct = {
    orderId: BytesLike;
    recipient: AddressLike;
    amount: BigNumberish;
    country: string;
    timestamp: BigNumberish;
    status: BigNumberish;
  };

  export type PayoutRequestStructOutput = [
    orderId: string,
    recipient: string,
    amount: bigint,
    country: string,
    timestamp: bigint,
    status: bigint
  ] & {
    orderId: string;
    recipient: string;
    amount: bigint;
    country: string;
    timestamp: bigint;
    status: bigint;
  };
}

export interface PayoutExecutorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "UPGRADE_INTERFACE_VERSION"
      | "acceptOwnership"
      | "canExecutePayout"
      | "dailyPayoutLimit"
      | "dailyPayoutSum"
      | "executePayout"
      | "getDailyPayoutSum"
      | "getMonthlyPayoutSum"
      | "getPayoutRequest"
      | "initialize"
      | "monthlyPayoutLimit"
      | "monthlyPayoutSum"
      | "owner"
      | "payoutRequests"
      | "pendingOwner"
      | "proxiableUUID"
      | "renounceOwnership"
      | "setDailyLimit"
      | "setMonthlyLimit"
      | "transferOwnership"
      | "treasuryController"
      | "upgradeToAndCall"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DailyLimitSet"
      | "Initialized"
      | "MonthlyLimitSet"
      | "OwnershipTransferStarted"
      | "OwnershipTransferred"
      | "PayoutExecuted"
      | "Upgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "canExecutePayout",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "dailyPayoutLimit",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "dailyPayoutSum",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executePayout",
    values: [BytesLike, AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getDailyPayoutSum",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMonthlyPayoutSum",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPayoutRequest",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "monthlyPayoutLimit",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "monthlyPayoutSum",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "payoutRequests",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setDailyLimit",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMonthlyLimit",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "treasuryController",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "canExecutePayout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dailyPayoutLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dailyPayoutSum",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executePayout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDailyPayoutSum",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMonthlyPayoutSum",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPayoutRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "monthlyPayoutLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "monthlyPayoutSum",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "payoutRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDailyLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMonthlyLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "treasuryController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
}

export namespace DailyLimitSetEvent {
  export type InputTuple = [country: string, newLimit: BigNumberish];
  export type OutputTuple = [country: string, newLimit: bigint];
  export interface OutputObject {
    country: string;
    newLimit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MonthlyLimitSetEvent {
  export type InputTuple = [country: string, newLimit: BigNumberish];
  export type OutputTuple = [country: string, newLimit: bigint];
  export interface OutputObject {
    country: string;
    newLimit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferStartedEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PayoutExecutedEvent {
  export type InputTuple = [
    orderId: BytesLike,
    recipient: AddressLike,
    amount: BigNumberish,
    country: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    orderId: string,
    recipient: string,
    amount: bigint,
    country: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    orderId: string;
    recipient: string;
    amount: bigint;
    country: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PayoutExecutor extends BaseContract {
  connect(runner?: ContractRunner | null): PayoutExecutor;
  waitForDeployment(): Promise<this>;

  interface: PayoutExecutorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  canExecutePayout: TypedContractMethod<
    [country: string, amount: BigNumberish],
    [boolean],
    "view"
  >;

  dailyPayoutLimit: TypedContractMethod<[arg0: string], [bigint], "view">;

  dailyPayoutSum: TypedContractMethod<
    [arg0: string, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  executePayout: TypedContractMethod<
    [
      orderId: BytesLike,
      recipient: AddressLike,
      amount: BigNumberish,
      country: string
    ],
    [boolean],
    "nonpayable"
  >;

  getDailyPayoutSum: TypedContractMethod<
    [country: string, dayKey: BigNumberish],
    [bigint],
    "view"
  >;

  getMonthlyPayoutSum: TypedContractMethod<
    [country: string, monthKey: BigNumberish],
    [bigint],
    "view"
  >;

  getPayoutRequest: TypedContractMethod<
    [orderId: BytesLike],
    [PayoutExecutor.PayoutRequestStructOutput],
    "view"
  >;

  initialize: TypedContractMethod<
    [owner: AddressLike, _treasuryController: AddressLike],
    [void],
    "nonpayable"
  >;

  monthlyPayoutLimit: TypedContractMethod<[arg0: string], [bigint], "view">;

  monthlyPayoutSum: TypedContractMethod<
    [arg0: string, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  payoutRequests: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, string, bigint, bigint] & {
        orderId: string;
        recipient: string;
        amount: bigint;
        country: string;
        timestamp: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  pendingOwner: TypedContractMethod<[], [string], "view">;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setDailyLimit: TypedContractMethod<
    [country: string, limit: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMonthlyLimit: TypedContractMethod<
    [country: string, limit: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasuryController: TypedContractMethod<[], [string], "view">;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "canExecutePayout"
  ): TypedContractMethod<
    [country: string, amount: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "dailyPayoutLimit"
  ): TypedContractMethod<[arg0: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "dailyPayoutSum"
  ): TypedContractMethod<[arg0: string, arg1: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "executePayout"
  ): TypedContractMethod<
    [
      orderId: BytesLike,
      recipient: AddressLike,
      amount: BigNumberish,
      country: string
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getDailyPayoutSum"
  ): TypedContractMethod<
    [country: string, dayKey: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMonthlyPayoutSum"
  ): TypedContractMethod<
    [country: string, monthKey: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPayoutRequest"
  ): TypedContractMethod<
    [orderId: BytesLike],
    [PayoutExecutor.PayoutRequestStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [owner: AddressLike, _treasuryController: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "monthlyPayoutLimit"
  ): TypedContractMethod<[arg0: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "monthlyPayoutSum"
  ): TypedContractMethod<[arg0: string, arg1: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "payoutRequests"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, string, bigint, bigint] & {
        orderId: string;
        recipient: string;
        amount: bigint;
        country: string;
        timestamp: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "pendingOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDailyLimit"
  ): TypedContractMethod<
    [country: string, limit: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMonthlyLimit"
  ): TypedContractMethod<
    [country: string, limit: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasuryController"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getEvent(
    key: "DailyLimitSet"
  ): TypedContractEvent<
    DailyLimitSetEvent.InputTuple,
    DailyLimitSetEvent.OutputTuple,
    DailyLimitSetEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "MonthlyLimitSet"
  ): TypedContractEvent<
    MonthlyLimitSetEvent.InputTuple,
    MonthlyLimitSetEvent.OutputTuple,
    MonthlyLimitSetEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferStarted"
  ): TypedContractEvent<
    OwnershipTransferStartedEvent.InputTuple,
    OwnershipTransferStartedEvent.OutputTuple,
    OwnershipTransferStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PayoutExecuted"
  ): TypedContractEvent<
    PayoutExecutedEvent.InputTuple,
    PayoutExecutedEvent.OutputTuple,
    PayoutExecutedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "DailyLimitSet(string,uint256)": TypedContractEvent<
      DailyLimitSetEvent.InputTuple,
      DailyLimitSetEvent.OutputTuple,
      DailyLimitSetEvent.OutputObject
    >;
    DailyLimitSet: TypedContractEvent<
      DailyLimitSetEvent.InputTuple,
      DailyLimitSetEvent.OutputTuple,
      DailyLimitSetEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "MonthlyLimitSet(string,uint256)": TypedContractEvent<
      MonthlyLimitSetEvent.InputTuple,
      MonthlyLimitSetEvent.OutputTuple,
      MonthlyLimitSetEvent.OutputObject
    >;
    MonthlyLimitSet: TypedContractEvent<
      MonthlyLimitSetEvent.InputTuple,
      MonthlyLimitSetEvent.OutputTuple,
      MonthlyLimitSetEvent.OutputObject
    >;

    "OwnershipTransferStarted(address,address)": TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;
    OwnershipTransferStarted: TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PayoutExecuted(bytes32,address,uint256,string,uint256)": TypedContractEvent<
      PayoutExecutedEvent.InputTuple,
      PayoutExecutedEvent.OutputTuple,
      PayoutExecutedEvent.OutputObject
    >;
    PayoutExecuted: TypedContractEvent<
      PayoutExecutedEvent.InputTuple,
      PayoutExecutedEvent.OutputTuple,
      PayoutExecutedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
