/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface VariableTimelockControllerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancel"
      | "delaysByActionType"
      | "execute"
      | "getDelayForActionType"
      | "initialize"
      | "isOperationDone"
      | "isOperationPending"
      | "isOperationReady"
      | "operationExecuted"
      | "operationTimestamps"
      | "owner"
      | "renounceOwnership"
      | "scheduleWithSeverity"
      | "timeUntilReady"
      | "transferOwnership"
      | "updateActionDelay"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ActionDelayUpdated"
      | "Initialized"
      | "OperationCancelled"
      | "OperationExecuted"
      | "OperationScheduled"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(functionFragment: "cancel", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "delaysByActionType",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "execute",
    values: [
      AddressLike,
      BigNumberish,
      BytesLike,
      BytesLike,
      BytesLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getDelayForActionType",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "isOperationDone",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isOperationPending",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isOperationReady",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "operationExecuted",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "operationTimestamps",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "scheduleWithSeverity",
    values: [
      AddressLike,
      BigNumberish,
      BytesLike,
      BytesLike,
      BytesLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "timeUntilReady",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateActionDelay",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "cancel", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "delaysByActionType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDelayForActionType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isOperationDone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isOperationPending",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isOperationReady",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "operationExecuted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "operationTimestamps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scheduleWithSeverity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "timeUntilReady",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateActionDelay",
    data: BytesLike
  ): Result;
}

export namespace ActionDelayUpdatedEvent {
  export type InputTuple = [
    severity: BigNumberish,
    oldDelay: BigNumberish,
    newDelay: BigNumberish
  ];
  export type OutputTuple = [
    severity: bigint,
    oldDelay: bigint,
    newDelay: bigint
  ];
  export interface OutputObject {
    severity: bigint;
    oldDelay: bigint;
    newDelay: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [
    owner: AddressLike,
    delays: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ];
  export type OutputTuple = [
    owner: string,
    delays: [bigint, bigint, bigint, bigint]
  ];
  export interface OutputObject {
    owner: string;
    delays: [bigint, bigint, bigint, bigint];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OperationCancelledEvent {
  export type InputTuple = [operationId: BytesLike];
  export type OutputTuple = [operationId: string];
  export interface OutputObject {
    operationId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OperationExecutedEvent {
  export type InputTuple = [
    operationId: BytesLike,
    target: AddressLike,
    data: BytesLike
  ];
  export type OutputTuple = [operationId: string, target: string, data: string];
  export interface OutputObject {
    operationId: string;
    target: string;
    data: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OperationScheduledEvent {
  export type InputTuple = [
    operationId: BytesLike,
    severity: BigNumberish,
    delay: BigNumberish,
    readyTimestamp: BigNumberish
  ];
  export type OutputTuple = [
    operationId: string,
    severity: bigint,
    delay: bigint,
    readyTimestamp: bigint
  ];
  export interface OutputObject {
    operationId: string;
    severity: bigint;
    delay: bigint;
    readyTimestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VariableTimelockController extends BaseContract {
  connect(runner?: ContractRunner | null): VariableTimelockController;
  waitForDeployment(): Promise<this>;

  interface: VariableTimelockControllerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancel: TypedContractMethod<[operationId: BytesLike], [void], "nonpayable">;

  delaysByActionType: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  execute: TypedContractMethod<
    [
      target: AddressLike,
      value: BigNumberish,
      data: BytesLike,
      predecessor: BytesLike,
      salt: BytesLike,
      severity: BigNumberish
    ],
    [void],
    "payable"
  >;

  getDelayForActionType: TypedContractMethod<
    [severity: BigNumberish],
    [bigint],
    "view"
  >;

  initialize: TypedContractMethod<
    [
      owner: AddressLike,
      emergencyDelay: BigNumberish,
      criticalDelay: BigNumberish,
      importantDelay: BigNumberish,
      routineDelay: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  isOperationDone: TypedContractMethod<
    [operationId: BytesLike],
    [boolean],
    "view"
  >;

  isOperationPending: TypedContractMethod<
    [operationId: BytesLike],
    [boolean],
    "view"
  >;

  isOperationReady: TypedContractMethod<
    [operationId: BytesLike],
    [boolean],
    "view"
  >;

  operationExecuted: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  operationTimestamps: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  scheduleWithSeverity: TypedContractMethod<
    [
      target: AddressLike,
      value: BigNumberish,
      data: BytesLike,
      predecessor: BytesLike,
      salt: BytesLike,
      severity: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  timeUntilReady: TypedContractMethod<
    [operationId: BytesLike],
    [bigint],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateActionDelay: TypedContractMethod<
    [severity: BigNumberish, newDelay: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancel"
  ): TypedContractMethod<[operationId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "delaysByActionType"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "execute"
  ): TypedContractMethod<
    [
      target: AddressLike,
      value: BigNumberish,
      data: BytesLike,
      predecessor: BytesLike,
      salt: BytesLike,
      severity: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getDelayForActionType"
  ): TypedContractMethod<[severity: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      owner: AddressLike,
      emergencyDelay: BigNumberish,
      criticalDelay: BigNumberish,
      importantDelay: BigNumberish,
      routineDelay: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isOperationDone"
  ): TypedContractMethod<[operationId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isOperationPending"
  ): TypedContractMethod<[operationId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isOperationReady"
  ): TypedContractMethod<[operationId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "operationExecuted"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "operationTimestamps"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "scheduleWithSeverity"
  ): TypedContractMethod<
    [
      target: AddressLike,
      value: BigNumberish,
      data: BytesLike,
      predecessor: BytesLike,
      salt: BytesLike,
      severity: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "timeUntilReady"
  ): TypedContractMethod<[operationId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateActionDelay"
  ): TypedContractMethod<
    [severity: BigNumberish, newDelay: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ActionDelayUpdated"
  ): TypedContractEvent<
    ActionDelayUpdatedEvent.InputTuple,
    ActionDelayUpdatedEvent.OutputTuple,
    ActionDelayUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "OperationCancelled"
  ): TypedContractEvent<
    OperationCancelledEvent.InputTuple,
    OperationCancelledEvent.OutputTuple,
    OperationCancelledEvent.OutputObject
  >;
  getEvent(
    key: "OperationExecuted"
  ): TypedContractEvent<
    OperationExecutedEvent.InputTuple,
    OperationExecutedEvent.OutputTuple,
    OperationExecutedEvent.OutputObject
  >;
  getEvent(
    key: "OperationScheduled"
  ): TypedContractEvent<
    OperationScheduledEvent.InputTuple,
    OperationScheduledEvent.OutputTuple,
    OperationScheduledEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "ActionDelayUpdated(uint8,uint256,uint256)": TypedContractEvent<
      ActionDelayUpdatedEvent.InputTuple,
      ActionDelayUpdatedEvent.OutputTuple,
      ActionDelayUpdatedEvent.OutputObject
    >;
    ActionDelayUpdated: TypedContractEvent<
      ActionDelayUpdatedEvent.InputTuple,
      ActionDelayUpdatedEvent.OutputTuple,
      ActionDelayUpdatedEvent.OutputObject
    >;

    "Initialized(address,uint256[4])": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "OperationCancelled(bytes32)": TypedContractEvent<
      OperationCancelledEvent.InputTuple,
      OperationCancelledEvent.OutputTuple,
      OperationCancelledEvent.OutputObject
    >;
    OperationCancelled: TypedContractEvent<
      OperationCancelledEvent.InputTuple,
      OperationCancelledEvent.OutputTuple,
      OperationCancelledEvent.OutputObject
    >;

    "OperationExecuted(bytes32,address,bytes)": TypedContractEvent<
      OperationExecutedEvent.InputTuple,
      OperationExecutedEvent.OutputTuple,
      OperationExecutedEvent.OutputObject
    >;
    OperationExecuted: TypedContractEvent<
      OperationExecutedEvent.InputTuple,
      OperationExecutedEvent.OutputTuple,
      OperationExecutedEvent.OutputObject
    >;

    "OperationScheduled(bytes32,uint8,uint256,uint256)": TypedContractEvent<
      OperationScheduledEvent.InputTuple,
      OperationScheduledEvent.OutputTuple,
      OperationScheduledEvent.OutputObject
    >;
    OperationScheduled: TypedContractEvent<
      OperationScheduledEvent.InputTuple,
      OperationScheduledEvent.OutputTuple,
      OperationScheduledEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
