/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IDynamicValidatorRegistry,
  IDynamicValidatorRegistryInterface,
} from "../../../Contracts/TreasuryController.sol/IDynamicValidatorRegistry";

const _abi = [
  {
    inputs: [],
    name: "getActiveValidators",
    outputs: [
      {
        internalType: "address[]",
        name: "",
        type: "address[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint8",
        name: "actionType",
        type: "uint8",
      },
    ],
    name: "getRequiredSignatures",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IDynamicValidatorRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IDynamicValidatorRegistryInterface {
    return new Interface(_abi) as IDynamicValidatorRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IDynamicValidatorRegistry {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IDynamicValidatorRegistry;
  }
}
