/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IVariableTimelock,
  IVariableTimelockInterface,
} from "../../../Contracts/UpgradeGovernor.sol/IVariableTimelock";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "target",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
      {
        internalType: "bytes32",
        name: "predecessor",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "salt",
        type: "bytes32",
      },
      {
        internalType: "enum IVariableTimelock.ActionSeverity",
        name: "severity",
        type: "uint8",
      },
    ],
    name: "execute",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "target",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
      {
        internalType: "bytes32",
        name: "predecessor",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "salt",
        type: "bytes32",
      },
      {
        internalType: "enum IVariableTimelock.ActionSeverity",
        name: "severity",
        type: "uint8",
      },
    ],
    name: "scheduleWithSeverity",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IVariableTimelock__factory {
  static readonly abi = _abi;
  static createInterface(): IVariableTimelockInterface {
    return new Interface(_abi) as IVariableTimelockInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IVariableTimelock {
    return new Contract(address, _abi, runner) as unknown as IVariableTimelock;
  }
}
