/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  MockUniswapV3Router,
  MockUniswapV3RouterInterface,
} from "../../Contracts/MockUniswapV3Router";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes",
            name: "path",
            type: "bytes",
          },
          {
            internalType: "address",
            name: "recipient",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "deadline",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "amountIn",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "amountOutMinimum",
            type: "uint256",
          },
        ],
        internalType: "struct MockUniswapV3Router.ExactInputSingleParams",
        name: "params",
        type: "tuple",
      },
    ],
    name: "exactInputSingle",
    outputs: [
      {
        internalType: "uint256",
        name: "amountOut",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

const _bytecode =
  "0x6080806040523461001657610243908161001b8239f35b5f80fdfe6080806040526004908136101561001f575b5050361561001d575f80fd5b005b5f3560e01c63740364460361001157602091600319838136011261018b57813567ffffffffffffffff9182821161018b5760a08236039182011261018b5783820135906022190181121561018b57810193838501359483861161018b5760240194803603861361018b5760141161018b5785816064815f82870135996323b872dd60e01b8352338a8401523060248401528a60448401523560601c5af180156101cc57610199575b508315158061018f575b6100e1575b505050604051908152f35b602401356001600160a01b038116810361018b575f80808681945af1903d15610185573d9081116101725760405190610123601f8201601f19168701836101d7565b81525f853d92013e5b156101385780806100d6565b60405162461bcd60e51b81529081018390526013602482015272115512081d1c985b9cd9995c8819985a5b1959606a1b6044820152606490fd5b604183634e487b7160e01b5f525260245ffd5b5061012c565b5f80fd5b50834710156100d1565b8581813d83116101c5575b6101ae81836101d7565b8101031261018b57518015150361018b575f6100c7565b503d6101a4565b6040513d5f823e3d90fd5b90601f8019910116810190811067ffffffffffffffff8211176101f957604052565b634e487b7160e01b5f52604160045260245ffdfea26469706673582212205297dfbb4049560384184fae85a97c6af9141e9cf13f3fa69223da3e22ab306364736f6c63430008180033";

type MockUniswapV3RouterConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockUniswapV3RouterConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockUniswapV3Router__factory extends ContractFactory {
  constructor(...args: MockUniswapV3RouterConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockUniswapV3Router & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): MockUniswapV3Router__factory {
    return super.connect(runner) as MockUniswapV3Router__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockUniswapV3RouterInterface {
    return new Interface(_abi) as MockUniswapV3RouterInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockUniswapV3Router {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as MockUniswapV3Router;
  }
}
