/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace GasRefiller {
  export type ManagedWalletStruct = {
    wallet: AddressLike;
    country: string;
    maxBalance: BigNumberish;
    active: boolean;
  };

  export type ManagedWalletStructOutput = [
    wallet: string,
    country: string,
    maxBalance: bigint,
    active: boolean
  ] & { wallet: string; country: string; maxBalance: bigint; active: boolean };
}

export interface GasRefillerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "UPGRADE_INTERFACE_VERSION"
      | "acceptOwnership"
      | "addManagedWallet"
      | "contractGasReserves"
      | "getActiveManagedWallets"
      | "initialize"
      | "isWalletManaged"
      | "managedWallets"
      | "needsRefill"
      | "owner"
      | "pendingOwner"
      | "proxiableUUID"
      | "receiveFees"
      | "refillContractGas"
      | "registerContractGasReserve"
      | "registeredContracts"
      | "removeManagedWallet"
      | "renounceOwnership"
      | "slippageTolerance"
      | "swapFeesToMatic"
      | "swapRouter"
      | "transferOwnership"
      | "upgradeToAndCall"
      | "usdc"
      | "usdcAccumulated"
      | "usdt"
      | "usdtAccumulated"
      | "walletIndex"
      | "withdrawMatic"
      | "wmatic"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BalanceRebalanced"
      | "ContractRefilled"
      | "ContractRegistered"
      | "FeeCollected"
      | "FeesSwapped"
      | "Initialized"
      | "OwnershipTransferStarted"
      | "OwnershipTransferred"
      | "Upgraded"
      | "WalletAdded"
      | "WalletRemoved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addManagedWallet",
    values: [AddressLike, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "contractGasReserves",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveManagedWallets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike, AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isWalletManaged",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "managedWallets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "needsRefill",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "receiveFees",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "refillContractGas",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerContractGasReserve",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registeredContracts",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeManagedWallet",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "slippageTolerance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "swapFeesToMatic",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapRouter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "usdcAccumulated",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "usdt", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "usdtAccumulated",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "walletIndex",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawMatic",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "wmatic", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addManagedWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contractGasReserves",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveManagedWallets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isWalletManaged",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "managedWallets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "needsRefill",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receiveFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "refillContractGas",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerContractGasReserve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registeredContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeManagedWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "slippageTolerance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapFeesToMatic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "swapRouter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "usdcAccumulated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "usdtAccumulated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "walletIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawMatic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "wmatic", data: BytesLike): Result;
}

export namespace BalanceRebalancedEvent {
  export type InputTuple = [
    wallets: AddressLike[],
    newBalances: BigNumberish[]
  ];
  export type OutputTuple = [wallets: string[], newBalances: bigint[]];
  export interface OutputObject {
    wallets: string[];
    newBalances: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContractRefilledEvent {
  export type InputTuple = [
    contract_: AddressLike,
    maticsReceived: BigNumberish,
    newBalance: BigNumberish
  ];
  export type OutputTuple = [
    contract_: string,
    maticsReceived: bigint,
    newBalance: bigint
  ];
  export interface OutputObject {
    contract_: string;
    maticsReceived: bigint;
    newBalance: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContractRegisteredEvent {
  export type InputTuple = [
    contract_: AddressLike,
    targetMatic: BigNumberish,
    thresholdMatic: BigNumberish
  ];
  export type OutputTuple = [
    contract_: string,
    targetMatic: bigint,
    thresholdMatic: bigint
  ];
  export interface OutputObject {
    contract_: string;
    targetMatic: bigint;
    thresholdMatic: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeCollectedEvent {
  export type InputTuple = [token: AddressLike, amount: BigNumberish];
  export type OutputTuple = [token: string, amount: bigint];
  export interface OutputObject {
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeesSwappedEvent {
  export type InputTuple = [
    token: AddressLike,
    amountIn: BigNumberish,
    maticsOut: BigNumberish
  ];
  export type OutputTuple = [
    token: string,
    amountIn: bigint,
    maticsOut: bigint
  ];
  export interface OutputObject {
    token: string;
    amountIn: bigint;
    maticsOut: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferStartedEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WalletAddedEvent {
  export type InputTuple = [
    wallet: AddressLike,
    country: string,
    maxBalance: BigNumberish
  ];
  export type OutputTuple = [
    wallet: string,
    country: string,
    maxBalance: bigint
  ];
  export interface OutputObject {
    wallet: string;
    country: string;
    maxBalance: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WalletRemovedEvent {
  export type InputTuple = [wallet: AddressLike];
  export type OutputTuple = [wallet: string];
  export interface OutputObject {
    wallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GasRefiller extends BaseContract {
  connect(runner?: ContractRunner | null): GasRefiller;
  waitForDeployment(): Promise<this>;

  interface: GasRefillerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  addManagedWallet: TypedContractMethod<
    [wallet: AddressLike, country: string, maxBalance: BigNumberish],
    [void],
    "nonpayable"
  >;

  contractGasReserves: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, boolean] & {
        contractAddress: string;
        targetMatic: bigint;
        thresholdMatic: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  getActiveManagedWallets: TypedContractMethod<
    [],
    [GasRefiller.ManagedWalletStructOutput[]],
    "view"
  >;

  initialize: TypedContractMethod<
    [
      owner: AddressLike,
      _router: AddressLike,
      _usdc: AddressLike,
      _usdt: AddressLike,
      _wmatic: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  isWalletManaged: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  managedWallets: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, boolean] & {
        wallet: string;
        country: string;
        maxBalance: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  needsRefill: TypedContractMethod<[contract_: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pendingOwner: TypedContractMethod<[], [string], "view">;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  receiveFees: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  refillContractGas: TypedContractMethod<
    [contract_: AddressLike, amountMatic: BigNumberish],
    [void],
    "nonpayable"
  >;

  registerContractGasReserve: TypedContractMethod<
    [
      contract_: AddressLike,
      targetMatic: BigNumberish,
      thresholdMatic: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  registeredContracts: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  removeManagedWallet: TypedContractMethod<
    [wallet: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  slippageTolerance: TypedContractMethod<[], [bigint], "view">;

  swapFeesToMatic: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish, minMaticOut: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  swapRouter: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  usdc: TypedContractMethod<[], [string], "view">;

  usdcAccumulated: TypedContractMethod<[], [bigint], "view">;

  usdt: TypedContractMethod<[], [string], "view">;

  usdtAccumulated: TypedContractMethod<[], [bigint], "view">;

  walletIndex: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  withdrawMatic: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  wmatic: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addManagedWallet"
  ): TypedContractMethod<
    [wallet: AddressLike, country: string, maxBalance: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "contractGasReserves"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, boolean] & {
        contractAddress: string;
        targetMatic: bigint;
        thresholdMatic: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getActiveManagedWallets"
  ): TypedContractMethod<[], [GasRefiller.ManagedWalletStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      owner: AddressLike,
      _router: AddressLike,
      _usdc: AddressLike,
      _usdt: AddressLike,
      _wmatic: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isWalletManaged"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "managedWallets"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, boolean] & {
        wallet: string;
        country: string;
        maxBalance: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "needsRefill"
  ): TypedContractMethod<[contract_: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "receiveFees"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "refillContractGas"
  ): TypedContractMethod<
    [contract_: AddressLike, amountMatic: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerContractGasReserve"
  ): TypedContractMethod<
    [
      contract_: AddressLike,
      targetMatic: BigNumberish,
      thresholdMatic: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registeredContracts"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "removeManagedWallet"
  ): TypedContractMethod<[wallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "slippageTolerance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "swapFeesToMatic"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish, minMaticOut: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swapRouter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "usdcAccumulated"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "usdt"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "usdtAccumulated"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "walletIndex"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdrawMatic"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "wmatic"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "BalanceRebalanced"
  ): TypedContractEvent<
    BalanceRebalancedEvent.InputTuple,
    BalanceRebalancedEvent.OutputTuple,
    BalanceRebalancedEvent.OutputObject
  >;
  getEvent(
    key: "ContractRefilled"
  ): TypedContractEvent<
    ContractRefilledEvent.InputTuple,
    ContractRefilledEvent.OutputTuple,
    ContractRefilledEvent.OutputObject
  >;
  getEvent(
    key: "ContractRegistered"
  ): TypedContractEvent<
    ContractRegisteredEvent.InputTuple,
    ContractRegisteredEvent.OutputTuple,
    ContractRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "FeeCollected"
  ): TypedContractEvent<
    FeeCollectedEvent.InputTuple,
    FeeCollectedEvent.OutputTuple,
    FeeCollectedEvent.OutputObject
  >;
  getEvent(
    key: "FeesSwapped"
  ): TypedContractEvent<
    FeesSwappedEvent.InputTuple,
    FeesSwappedEvent.OutputTuple,
    FeesSwappedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferStarted"
  ): TypedContractEvent<
    OwnershipTransferStartedEvent.InputTuple,
    OwnershipTransferStartedEvent.OutputTuple,
    OwnershipTransferStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;
  getEvent(
    key: "WalletAdded"
  ): TypedContractEvent<
    WalletAddedEvent.InputTuple,
    WalletAddedEvent.OutputTuple,
    WalletAddedEvent.OutputObject
  >;
  getEvent(
    key: "WalletRemoved"
  ): TypedContractEvent<
    WalletRemovedEvent.InputTuple,
    WalletRemovedEvent.OutputTuple,
    WalletRemovedEvent.OutputObject
  >;

  filters: {
    "BalanceRebalanced(address[],uint256[])": TypedContractEvent<
      BalanceRebalancedEvent.InputTuple,
      BalanceRebalancedEvent.OutputTuple,
      BalanceRebalancedEvent.OutputObject
    >;
    BalanceRebalanced: TypedContractEvent<
      BalanceRebalancedEvent.InputTuple,
      BalanceRebalancedEvent.OutputTuple,
      BalanceRebalancedEvent.OutputObject
    >;

    "ContractRefilled(address,uint256,uint256)": TypedContractEvent<
      ContractRefilledEvent.InputTuple,
      ContractRefilledEvent.OutputTuple,
      ContractRefilledEvent.OutputObject
    >;
    ContractRefilled: TypedContractEvent<
      ContractRefilledEvent.InputTuple,
      ContractRefilledEvent.OutputTuple,
      ContractRefilledEvent.OutputObject
    >;

    "ContractRegistered(address,uint256,uint256)": TypedContractEvent<
      ContractRegisteredEvent.InputTuple,
      ContractRegisteredEvent.OutputTuple,
      ContractRegisteredEvent.OutputObject
    >;
    ContractRegistered: TypedContractEvent<
      ContractRegisteredEvent.InputTuple,
      ContractRegisteredEvent.OutputTuple,
      ContractRegisteredEvent.OutputObject
    >;

    "FeeCollected(address,uint256)": TypedContractEvent<
      FeeCollectedEvent.InputTuple,
      FeeCollectedEvent.OutputTuple,
      FeeCollectedEvent.OutputObject
    >;
    FeeCollected: TypedContractEvent<
      FeeCollectedEvent.InputTuple,
      FeeCollectedEvent.OutputTuple,
      FeeCollectedEvent.OutputObject
    >;

    "FeesSwapped(address,uint256,uint256)": TypedContractEvent<
      FeesSwappedEvent.InputTuple,
      FeesSwappedEvent.OutputTuple,
      FeesSwappedEvent.OutputObject
    >;
    FeesSwapped: TypedContractEvent<
      FeesSwappedEvent.InputTuple,
      FeesSwappedEvent.OutputTuple,
      FeesSwappedEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "OwnershipTransferStarted(address,address)": TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;
    OwnershipTransferStarted: TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;

    "WalletAdded(address,string,uint256)": TypedContractEvent<
      WalletAddedEvent.InputTuple,
      WalletAddedEvent.OutputTuple,
      WalletAddedEvent.OutputObject
    >;
    WalletAdded: TypedContractEvent<
      WalletAddedEvent.InputTuple,
      WalletAddedEvent.OutputTuple,
      WalletAddedEvent.OutputObject
    >;

    "WalletRemoved(address)": TypedContractEvent<
      WalletRemovedEvent.InputTuple,
      WalletRemovedEvent.OutputTuple,
      WalletRemovedEvent.OutputObject
    >;
    WalletRemoved: TypedContractEvent<
      WalletRemovedEvent.InputTuple,
      WalletRemovedEvent.OutputTuple,
      WalletRemovedEvent.OutputObject
    >;
  };
}
